name: Evenrud Fuglehundsenter
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e8e705c8-16fd-45da-bc66-0b82fa5a081b.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7bbfde36-3940-47df-986f-c439fa9292e7.png
layout_spectrum: 0.0733771444762144
typography_spectrum: 0.6725876306463033
analytics: {}
opengraph: {}
color:
  brandColors:
    - '#000000'
    - '#FF1E00'
    - '#4F0B01'
    - '#7A1102'
    - '#D81F04'
  brandStrength: 0.3595448431923137
  lightness: 0.5889401102942958
  saturation: 0.1918649874393376
  rhythmicContrast: 0.2931161226820901
purpose:
  - type: contact
    label: Contact us
    url: 'mailto:dagroger74@gmail.com'
title: Evenrud Fuglehundsenter
description: Hvor gode hunder blir til...
author:
  name: Dag Roger Berg
  email: dagroger@evenrud.biz
content_rating:
  adult: false
navigation:
  - name: Hunde Hotell
    id: 5cc4cf98-3e94-46b7-aeb0-d4e0a3bb4047
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c6dd039-2ee9-4117-8ad4-7c6665ae03c8.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c6dd039-2ee9-4117-8ad4-7c6665ae03c8.png
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
